/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package com.ilot.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// HISTORY_ALERT_SYSTEM
	VIEW_HISTORY_ALERT_SYSTEM("VIEW_HISTORY_ALERT_SYSTEM"),	
	CREATE_HISTORY_ALERT_SYSTEM("CREATE_HISTORY_ALERT_SYSTEM"),
	UPDATE_HISTORY_ALERT_SYSTEM("UPDATE_HISTORY_ALERT_SYSTEM"),
	DELETE_HISTORY_ALERT_SYSTEM("DELETE_HISTORY_ALERT_SYSTEM"),


	// DEPLOIEMENT_ROBOT_SONDE
	VIEW_DEPLOIEMENT_ROBOT_SONDE("VIEW_DEPLOIEMENT_ROBOT_SONDE"),
	CREATE_DEPLOIEMENT_ROBOT_SONDE("CREATE_DEPLOIEMENT_ROBOT_SONDE"),
	UPDATE_DEPLOIEMENT_ROBOT_SONDE("UPDATE_DEPLOIEMENT_ROBOT_SONDE"),
	DELETE_DEPLOIEMENT_ROBOT_SONDE("DELETE_DEPLOIEMENT_ROBOT_SONDE"),
	// ENVIRONMENT_CONFIG
	VIEW_ENVIRONMENT_CONFIG("VIEW_ENVIRONMENT_CONFIG"),
	CREATE_ENVIRONMENT_CONFIG("CREATE_ENVIRONMENT_CONFIG"),
	UPDATE_ENVIRONMENT_CONFIG("UPDATE_ENVIRONMENT_CONFIG"),
	DELETE_ENVIRONMENT_CONFIG("DELETE_ENVIRONMENT_CONFIG"),
	// FONCTIONNALITE
	VIEW_FONCTIONNALITE("VIEW_FONCTIONNALITE"),
	CREATE_FONCTIONNALITE("CREATE_FONCTIONNALITE"),
	UPDATE_FONCTIONNALITE("UPDATE_FONCTIONNALITE"),
	DELETE_FONCTIONNALITE("DELETE_FONCTIONNALITE"),
	// NRO
	VIEW_NRO("VIEW_NRO"),
	CREATE_NRO("CREATE_NRO"),
	UPDATE_NRO("UPDATE_NRO"),
	DELETE_NRO("DELETE_NRO"),
	// PROFIL
	VIEW_PROFIL("VIEW_PROFIL"),
	CREATE_PROFIL("CREATE_PROFIL"),
	UPDATE_PROFIL("UPDATE_PROFIL"),
	DELETE_PROFIL("DELETE_PROFIL"),
	// PROFIL_FONCTIONNALITE
	VIEW_PROFIL_FONCTIONNALITE("VIEW_PROFIL_FONCTIONNALITE"),
	CREATE_PROFIL_FONCTIONNALITE("CREATE_PROFIL_FONCTIONNALITE"),
	UPDATE_PROFIL_FONCTIONNALITE("UPDATE_PROFIL_FONCTIONNALITE"),
	DELETE_PROFIL_FONCTIONNALITE("DELETE_PROFIL_FONCTIONNALITE"),
	// ROBOT
	VIEW_ROBOT("VIEW_ROBOT"),
	CREATE_ROBOT("CREATE_ROBOT"),
	UPDATE_ROBOT("UPDATE_ROBOT"),
	DELETE_ROBOT("DELETE_ROBOT"),
	// ROBOT_VERSION
	VIEW_ROBOT_VERSION("VIEW_ROBOT_VERSION"),
	CREATE_ROBOT_VERSION("CREATE_ROBOT_VERSION"),
	UPDATE_ROBOT_VERSION("UPDATE_ROBOT_VERSION"),
	DELETE_ROBOT_VERSION("DELETE_ROBOT_VERSION"),
	// ROBOT_VERSION_FILES
	VIEW_ROBOT_VERSION_FILES("VIEW_ROBOT_VERSION_FILES"),
	CREATE_ROBOT_VERSION_FILES("CREATE_ROBOT_VERSION_FILES"),
	UPDATE_ROBOT_VERSION_FILES("UPDATE_ROBOT_VERSION_FILES"),
	DELETE_ROBOT_VERSION_FILES("DELETE_ROBOT_VERSION_FILES"),
	// SONDE
	VIEW_SONDE("VIEW_SONDE"),
	CREATE_SONDE("CREATE_SONDE"),
	UPDATE_SONDE("UPDATE_SONDE"),
	DELETE_SONDE("DELETE_SONDE"),
	// STATUT
	VIEW_STATUT("VIEW_STATUT"),
	CREATE_STATUT("CREATE_STATUT"),
	UPDATE_STATUT("UPDATE_STATUT"),
	DELETE_STATUT("DELETE_STATUT"),
	// USER
	VIEW_USER("VIEW_USER"),
	CREATE_USER("CREATE_USER"),
	UPDATE_USER("UPDATE_USER"),
	DELETE_USER("DELETE_USER"),


	// CONTACT
	CREATE_CONTACT("CREATE_CONTACT"),
	UPDATE_CONTACT("UPDATE_CONTACT"),
	DELETE_CONTACT("DELETE_CONTACT"),
	VIEW_CONTACT("VIEW_CONTACT"),

	// VARIABLE
	CREATE_VARIABLE("CREATE_VARIABLE"),
	UPDATE_VARIABLE("UPDATE_VARIABLE"),
	DELETE_VARIABLE("DELETE_VARIABLE"),
	VIEW_VARIABLE("VIEW_VARIABLE"),

	// VARIABLE EVENT
	CREATE_VARIABLE_EVENT("CREATE_VARIABLE_EVENT"),
	UPDATE_VARIABLE_EVENT("UPDATE_VARIABLE_EVENT"),
	DELETE_VARIABLE_EVENT("DELETE_VARIABLE_EVENT"),
	VIEW_VARIABLE_EVENT("VIEW_VARIABLE_EVENT"),

	// MESSAGE TEMPLATE
	CREATE_MESSAGE_TEMPLATE("CREATE_MESSAGE_TEMPLATE"),
	UPDATE_MESSAGE_TEMPLATE("UPDATE_MESSAGE_TEMPLATE"),
	DELETE_MESSAGE_TEMPLATE("DELETE_MESSAGE_TEMPLATE"),
	VIEW_MESSAGE_TEMPLATE("VIEW_MESSAGE_TEMPLATE"),


	// NOTIFICATION CONTACT
	CREATE_NOTIFICATION_CONTACT("CREATE_NOTIFICATION_CONTACT"),
	UPDATE_NOTIFICATION_CONTACT("UPDATE_NOTIFICATION_CONTACT"),
	DELETE_NOTIFICATION_CONTACT("DELETE_NOTIFICATION_CONTACT"),
	VIEW_NOTIFICATION_CONTACT("VIEW_NOTIFICATION_CONTACT"),



	// CRON EXPRESSION INFO
	CREATE_CRON_INFO("CREATE_CRON_INFO"),
	UPDATE_CRON_INFO("UPDATE_CRON_INFO"),
	DELETE_CRON_INFO("DELETE_CRON_INFO"),
	VIEW_CRON_INFO("VIEW_CRON_INFO"),


	// NOTIFICATION
	CREATE_NOTIFICATION("CREATE_NOTIFICATION"),
	UPDATE_NOTIFICATION("UPDATE_NOTIFICATION"),
	DELETE_NOTIFICATION("DELETE_NOTIFICATION"),
	VIEW_NOTIFICATION("VIEW_NOTIFICATION"),

	// EVENT
	CREATE_EVENT("CREATE_EVENT"),
	UPDATE_EVENT("UPDATE_EVENT"),
	DELETE_EVENT("DELETE_EVENT"),
	VIEW_EVENT("VIEW_EVENT"),

	// CRITERIA
	CREATE_CRITERIA("CREATE_CRITERIA"),
	UPDATE_CRITERIA("UPDATE_CRITERIA"),
	DELETE_CRITERIA("DELETE_CRITERIA"),
	VIEW_CRITERIA("VIEW_CRITERIA"),

	// NOTIFICATION CRITERIA
	CREATE_NOTIFICATION_CRITERIA("CREATE_NOTIFICATION_CRITERIA"),
	UPDATE_NOTIFICATION_CRITERIA("UPDATE_NOTIFICATION_CRITERIA"),
	DELETE_NOTIFICATION_CRITERIA("DELETE_NOTIFICATION_CRITERIA"),
	VIEW_NOTIFICATION_CRITERIA("VIEW_NOTIFICATION_CRITERIA"),


	// OPERATOR VARIABLE
	CREATE_OPERATOR_VARIABLE("CREATE_OPERATOR_VARIABLE"),
	UPDATE_OPERATOR_VARIABLE("UPDATE_OPERATOR_VARIABLE"),
	DELETE_OPERATOR_VARIABLE("DELETE_OPERATOR_VARIABLE"),
	VIEW_OPERATOR_VARIABLE("VIEW_OPERATOR_VARIABLE"),

	// CHANNEL
	CREATE_CHANNEL("CREATE_CHANNEL"),
	UPDATE_CHANNEL("UPDATE_CHANNEL"),
	DELETE_CHANNEL("DELETE_CHANNEL"),
	VIEW_CHANNEL("VIEW_CHANNEL"),

	// EVENT BOT
	CREATE_EVENT_BOT("CREATE_EVENT_BOT"),
	UPDATE_EVENT_BOT("UPDATE_EVENT_BOT"),
	DELETE_EVENT_BOT("DELETE_EVENT_BOT"),
	VIEW_EVENT_BOT("VIEW_EVENT_BOT"),


	CREATE_SMTP_SETTING("CREATE_SMTP_SETTING"),
	UPDATE_SMTP_SETTING("UPDATE_SMTP_SETTING"),
	DELETE_SMTP_SETTING("DELETE_SMTP_SETTING"),
	VIEW_SMTP_SETTING("VIEW_SMTP_SETTING"),


	CREATE_SMS_SETTING("CREATE_SMS_SETTING"),
	UPDATE_SMS_SETTING("UPDATE_SMS_SETTING"),
	DELETE_SMS_SETTING("DELETE_SMS_SETTING"),
	VIEW_SMS_SETTING("VIEW_SMS_SETTING"),







	//Parametrage
	CREATE_PARAM_PLAGE_ANALYSE("CREATE_PARAM_PLAGE_ANALYSE"),
	UPDATE_PARAM_PLAGE_ANALYSE("UPDATE_PARAM_PLAGE_ANALYSE"),
	DELETE_PARAM_PLAGE_ANALYSE("DELETE_PARAM_PLAGE_ANALYSE"),
	VIEW_PARAM_PLAGE_ANALYSE("VIEW_PARAM_PLAGE_ANALYSE"),

	//Parametrage seuil criticite
	CREATE_PARAM_SEUIL_CRITICITE("CREATE_PARAM_SEUIL_CRITICITE"),
	UPDATE_PARAM_SEUIL_CRITICITE("UPDATE_PARAM_SEUIL_CRITICITE"),
	DELETE_PARAM_SEUIL_CRITICITE("DELETE_PARAM_SEUIL_CRITICITE"),
	VIEW_PARAM_SEUIL_CRITICITE("VIEW_PARAM_SEUIL_CRITICITE"),

	// PARAM_KPI
	CREATE_PARAM_KPI("CREATE_PARAM_KPI"),
	UPDATE_PARAM_KPI("UPDATE_PARAM_KPI"),
	DELETE_PARAM_KPI("DELETE_PARAM_KPI"),
	VIEW_PARAM_KPI("VIEW_PARAM_KPI"),

	// EXECUTION_MANUELLE_ROBOT
	CREATE_EXECUTION_MANUELLE_ROBOT("CREATE_EXECUTION_MANUELLE_ROBOT"),
	UPDATE_EXECUTION_MANUELLE_ROBOT("UPDATE_EXECUTION_MANUELLE_ROBOT"),
	DELETE_EXECUTION_MANUELLE_ROBOT("DELETE_EXECUTION_MANUELLE_ROBOT"),
	VIEW_EXECUTION_MANUELLE_ROBOT("VIEW_EXECUTION_MANUELLE_ROBOT"),


	//StatausSceanrio
	CREATE_STATUS_SCENARIO("CREATE_STATUS_SCENARIO"),
	UPDATE_STATUS_SCENARIO("UPDATE_STATUS_SCENARIO"),
	DELETE_STATUS_SCENARIO("DELETE_STATUS_SCENARIO"),
	VIEW_STATUS_SCENARIO("VIEW_STATUS_SCENARIO"),


	// REFERENCE SCENARIO SONDE
	CREATE_REFERENCE_SCENARIO_SONDE("CREATE_REFERENCE_SCENARIO_SONDE"),
	UPDATE_REFERENCE_SCENARIO_SONDE("UPDATE_REFERENCE_SCENARIO_SONDE"),
	DELETE_REFERENCE_SCENARIO_SONDE("DELETE_REFERENCE_SCENARIO_SONDE"),
	VIEW_REFERENCE_SCENARIO_SONDE("VIEW_REFERENCE_SCENARIO_SONDE"),



	// ILOT
	CREATE_ILOT("CREATE_ILOT"),
	UPDATE_ILOT("UPDATE_ILOT"),
	DELETE_ILOT("DELETE_ILOT"),
	VIEW_ILOT("VIEW_ILOT"),

	// LOT
	CREATE_LOT("CREATE_LOT"),
	UPDATE_LOT("UPDATE_LOT"),
	DELETE_LOT("DELETE_LOT"),
	VIEW_LOT("VIEW_LOT"),

	// PROJET
	CREATE_PROJET("CREATE_PROJET"),
	UPDATE_PROJET("UPDATE_PROJET"),
	DELETE_PROJET("DELETE_PROJET"),
	VIEW_PROJET("VIEW_PROJET"),
	;



	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
